### ISSUE TITLE
実験の変更点と刺激（一部）の送付

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#13]
【実験の変更点について】
実験プログラムで文字の類似度に関する質問項目の後に、
①刺激がどれくらい文字に見えるか
②刺激を見てどれくらい不気味だと感じたか
③刺激を見てどれくらいゾワゾワしたか
の3問を尋ねる項目を追加していただきたいです。評定方法は全て類似度と同様の方法で行いたいと考えております。質問文は以下の通りです。
①どれくらい文字らしく見えたか、該当する割合(%)を選んでください。
②どれくらい不気味だと感じたか、該当する割合(%)を選んでください。
③どれくらいゾワゾワと感じたか、該当する割合(%)を選んでください。

【刺激（一部）の送付について】
予備実験で使用する刺激で完成したものを送付いたします。また、刺激の数は合計23個になります。

![か え](https://github.com/temochiz-lab/tuexp2024/assets/162528389/d2032495-e8c9-4b26-adf8-1613a235a4f0)
![く へ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/dd6212c6-012b-41be-bf46-e0c9f6f6d9be)
![た み](https://github.com/temochiz-lab/tuexp2024/assets/162528389/62cbff3b-099b-4454-8b8d-4a9100d834d8)
![よ を](https://github.com/temochiz-lab/tuexp2024/assets/162528389/c9cf0ec2-2ced-4c25-a87a-c384d0baba25)

ご確認のほどよろしくお願いいたします。

**Comment by temochiz-lab** [comment]
こちらは対応済なのでクローズします。
