### ISSUE TITLE
打ち合わせ後の実験プログラムの変更点について

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#14]
先日の打ち合わせとその後に決定した実験プログラムの変更点についてまとめました。

【類似度を質問する数直線の脇に書かれたひらがなのフォント】
・本試行：MS明朝
・練習試行：MSゴシック
・どちらも太さの変更はなし

【文字らしさ、不気味さ、ゾワゾワ感に関する始めの質問文の文面】
・どれくらい以下のように感じたか、該当する割合(%)を選んでください。

【刺激（本試行）について】
・フォント：MS明朝
・数：23個
・合体する文字数：2文字
・後日画像を送付します

【刺激（練習試行）について】
・フォント：MSゴシック
・数：2個
・合体する文字数：2文字
・使用する画像を添付します
![き み（練習試行用）](https://github.com/temochiz-lab/tuexp2024/assets/162528389/99837f19-42ad-4923-b13f-3b8d8f0fbbde)
![を あ（練習試行用）](https://github.com/temochiz-lab/tuexp2024/assets/162528389/5dc6ec2d-e4a9-4173-8953-2a51217467ad)

【休憩について】
・本試行を前半（11問）と後半（12問）に分け、前半終了後に「1分間目を閉じて休んでください。」と表示する
・キーを押すまたは「次へ」ボタンをクリックすると実験再開

お手数をおかけしますが、ご確認のほどよろしくお願いします。

**Comment by temochiz-lab** [comment]
話題4つで合っていますか?
①類似度を質問する数直線の脇に書かれたひらがなのフォント
・本試行：MS明朝
・練習試行：MSゴシック
②練習試行の画像差し替え
③本試行の画像差し替え
④休憩の設定

**Comment by temochiz-lab** [comment]
②完了、残り①③④

**Comment by temochiz-lab** [comment]
①完了、残り③④

**Comment by temochiz-lab** [comment]
③完了、残り①
教示文が1.5秒だけど、実際は1秒設定になっている件はどうします？
現状に合わせて教示文を1秒に直すのが良いかなと、、
https://github.com/temochiz-lab/tuexp2024/issues/11

**Comment by Aoki-Futaba** [comment]
設定に合わせて教示文を1秒に修正する形でお願いします。

**Comment by temochiz-lab** [comment]
確認済み。
