### ISSUE TITLE
予備実験の刺激画像の送付

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#16]
予備実験で使用する刺激（23個）が完成しましたのでお送りします。ご確認のほどよろしくお願いいたします。
![え か](https://github.com/temochiz-lab/tuexp2024/assets/162528389/36e71c4e-7204-4b36-ab1a-221b7f21cd9f)
![お り](https://github.com/temochiz-lab/tuexp2024/assets/162528389/338a7a9f-7576-4a7b-aed3-affe6b7ef8fe)
![き あ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/0485b995-13e2-48a1-95b8-b44f141eb3f4)
![く へ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/7ebf8ed9-2565-4184-b375-72365b410c84)
![け て](https://github.com/temochiz-lab/tuexp2024/assets/162528389/1f9d0db1-99ba-4504-aec6-f8b45f649400)
![こ う](https://github.com/temochiz-lab/tuexp2024/assets/162528389/6f4c49c0-cff1-4797-9324-475c761c6285)
![さ わ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/723956d8-33ec-474d-a90c-281cc6f2b402)
![し つ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/ac88ea08-b4ce-4e1d-9270-94058e73f4c5)
![せ ん](https://github.com/temochiz-lab/tuexp2024/assets/162528389/8514b22b-72bb-44ed-8a41-52527657ef5a)
![そ も](https://github.com/temochiz-lab/tuexp2024/assets/162528389/c6540b83-b544-465e-8a42-06aec6a1ffce)
![と る](https://github.com/temochiz-lab/tuexp2024/assets/162528389/a9dc0929-6270-43ad-999f-a35c491d4592)
![な に](https://github.com/temochiz-lab/tuexp2024/assets/162528389/2139ca63-ffef-4b3c-bd78-19a92f8094f5)
![ぬ す](https://github.com/temochiz-lab/tuexp2024/assets/162528389/86cbdc8b-1fb5-4b77-a9fb-c3f8dcaee567)
![は ら](https://github.com/temochiz-lab/tuexp2024/assets/162528389/db19a785-a3a7-478e-9e68-4f071024aa74)
![ひ の](https://github.com/temochiz-lab/tuexp2024/assets/162528389/66ffe32d-1997-4622-9490-36f9c1363c42)
![ふ ね](https://github.com/temochiz-lab/tuexp2024/assets/162528389/0503ad72-227d-407b-9e4d-170718c6ad36)
![ほ や](https://github.com/temochiz-lab/tuexp2024/assets/162528389/a875fffe-26e8-4484-891e-8c481fd4f83f)
![ま い](https://github.com/temochiz-lab/tuexp2024/assets/162528389/cc90ed08-a56f-4172-8776-51438fd573f8)
![み た](https://github.com/temochiz-lab/tuexp2024/assets/162528389/466475ec-db63-4618-84d0-24ee84001ae3)
![む ろ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/87210a78-4721-4e05-9a51-e115cbaa165b)
![め れ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/4d60629a-29e7-4632-b8aa-f6626191619e)
![ゆ ち](https://github.com/temochiz-lab/tuexp2024/assets/162528389/35610b7b-48fa-4b8f-a36a-a3cf86a49c1b)
![を よ](https://github.com/temochiz-lab/tuexp2024/assets/162528389/f6668f78-f2a2-42bf-931b-5944d62c8a9a)

**Comment by temochiz-lab** [comment]
ファイル名に通し番号を付けるのと、選択肢を間違えないようにしたいので、
名前を
1.jpg,2.jpg,3.jpg
とかにして、zipにまとめて添付できますでしょうか？

**Comment by Aoki-Futaba** [comment]
お世話になっております。
刺激画像に通し番号を付けました。ご確認のほどよろしくお願いします。
[Uploading 予備実験刺激.zip…]()

**Comment by Aoki-Futaba** [comment]
お世話になっております。刺激の名前を変更してzipファイルに圧縮したものをお送りします。ご確認のほどよろしくお願いします。
[予備実験刺激.zip](https://github.com/user-attachments/files/16043740/default.zip)

**Comment by temochiz-lab** [comment]
受け取れましたー
