### ISSUE TITLE
青木さんのプログラム編集について

### ISSUE THREAD

**Issue by WATANABEMe** [temochiz-lab/tuexp2024#18]
青木さんのプログラムのソーススクリプトを青木さんが編集できるようにしてもいいでしょうか。教示の文言を変更するだけですが，スクリプトをGIT上で編集してもいいのでしょうか。誤って他のところを変更してしまう恐れがあるので別のエディターで編集したほうがいいでしょうか。後者の場合，GITからダウンロードしてもらえばいいですか？青木さんはGITのアカウントつくってましたでしょうか。

**Comment by temochiz-lab** [comment]
gitの使い方としては、pull requestという、変更の申請をしてもらって反映させるのが正しいのですが、そこの辺りはややこしいので、一旦は自分のPCで編集してもらって、次回直接のミーティングの際に最新版としてgitに反映させる方法が良いと思います。

**Comment by WATANABEMe** [comment]
お返事ありがとうございます。青木さんに伝えます。
