### ISSUE TITLE
プログラムの変更点について

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#19]
お世話になっております。
本日の打ち合わせで決定した変更点をお伝えします。ご確認のほどよろしくお願いします。

①ボタンを日本語にする
②休憩から後半の試行に移る方法をキーボード操作にする

引き続きよろしくお願いいたします。

**Comment by temochiz-lab** [comment]
修正しました。　動作確認お願いします！
