### ISSUE TITLE
練習試行と本試行のボタンについて

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#20]
お世話になっております。修正ありがとうございました。
お忙しいところ恐縮ですが、練習試行と本試行のボタンが「Continue」でしたので、「次へ」への変更をお願いしてもよろしいでしょうか。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by temochiz-lab** [comment]
修正しましたので確認お願いします。
