### ISSUE TITLE
Excelでファイルを読んだときに日本語が化ける現象の対策(NTT ファイル)

### ISSUE THREAD

**Issue by ShimizuShoko** [temochiz-lab/tuexp2024#4]
[Uploading 03_familiarity_ntt2021.txt…]()

**Comment by ShimizuShoko** [comment]
[Uploading 03_familiarity_ntt2021.txt…]()

**Comment by temochiz-lab** [comment]
BOM付UTF-8にする必要があります。

Windowsでやる場合は
https://pcmatic.jp/faq/windows/10/

Macだとちょっと面倒ですね。
https://qiita.com/firedfly/items/f92add9d6ef07ed48bac

**Comment by ShimizuShoko** [comment]
NTTのファイルが読み込めなかった原因について、解説をお送りいただいてありがとうございます。MacBookを利用している学生が少なく、使い方に困ることが多いためとても助かりました。これからよろしくお願いいたします。
