### ISSUE TITLE
本日使用したPowerPointを送信します。

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#5]
お世話になっております。人間科学部心理学科3年の青木双葉です。
本日の打ち合わせで使用したPowerPointを送信いたします。ご確認のほどよろしくお願いします。

**Comment by temochiz-lab** [comment]
gitには添付できていないみたいですね💦

**Comment by Aoki-Futaba** [comment]
青木です。
ファイルが添付できておらず申し訳ございませんでした。再度お送りいたします。
[卒論 予備実験案 (MS明朝).pptx](https://github.com/temochiz-lab/tuexp2024/files/14524296/MS.pptx)

**Comment by temochiz-lab** [comment]
受け取れました！
第一弾作り始めます。
