### ISSUE TITLE
MSゴシックで作成した刺激のPowerPointを送信いたします。

### ISSUE THREAD

**Issue by Aoki-Futaba** [temochiz-lab/tuexp2024#7]
MSゴシックで作成した刺激のPowerPointが完成しましたので送信いたします。
実験全体の文章とスライダーの表示方法を変更しました。ご確認のほどよろしくお願いします。
[卒論 予備実験案 (MSゴシック).pptx](https://github.com/temochiz-lab/tuexp2024/files/14550283/MS.pptx)

**Comment by temochiz-lab** [comment]
受領しました。
